{
        'name': 'Hospital Managment',
        'version': '12.0.1.0.0',
        'summary': 'Record Information',
        'category': 'Tools',
        'author': 'Verts Services India Pvt. Ltd.',
        'website': 'https://www.verts.co.in',
        'sequence': '2',
        'description': '',
        'depends': ['base', 'mail','sale_management','website','website_form','product','stock'],
        'data': [
                'security/ir.model.access.csv',
                'data/sequence.xml',
                # 'data/mail_template.xml',
                'wizards/create_appointment.xml',
                'wizards/date_form_view.xml',
                'reports/sale_order_inh.xml',
                'reports/invoice_report_inh.xml',
                'reports/report.xml',
                'reports/hospital_card1.xml',
                'reports/new_report.xml',
                'view/hospital_views.xml',
                'view/website_form.xml',
                'view/templates.xml',
                'view/doctor_views.xml',
                'view/appointment_views.xml',
                'view/medicin_store.xml',
                'view/res_partner_views.xml',
                'view/sale_order_views.xml',
                'view/invoice_inherit.xml',
                'view/menu.xml',



        ],
        'images': [],
        'license': 'AGPL-3',
        'installable': True,
        'application': True,
        'auto_install': False,
}